site_name: Development Docs
theme:
  name: material

nav:
    - 'index.md'
    - 'variable_scss.md'
    - 'translation-plugin.md'
    - 'hoverover.md'
    - 'accordion.md'
    - 'sso.md'
    - 'reference_sites.md'